services:
  db:
    image: postgres:latest
    container_name: ruvds_bot_bd
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: sadwalther/crud:latest
    container_name: ruvds_bot
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: