services:
  app:
    image: sadwalther/crud:latest
    ports:
      - "8081:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: